const galleryItems = [
    {
        id: 1,
        src: "https://picsum.photos/800?random=1",
        type: "photography",
        title: "Urban Symmetry 1",
        artist: "Sarah Winters",
        likes: 272,
        comments: 21,
        size: "large",
        featured: false,
    },
    {
        id: 2,
        src: "https://picsum.photos/800?random=2",
        type: "art",
        title: "Abstract Dreams 2",
        artist: "James Lee",
        likes: 165,
        comments: 15,
        size: "tall",
        featured: false,
    },
    {
        id: 3,
        src: "https://picsum.photos/800?random=3",
        type: "digital",
        title: "Neon Nights 3",
        artist: "Elena Costa",
        likes: 191,
        comments: 17,
        size: "tall",
        featured: false,
    },
    {
        id: 4,
        src: "https://picsum.photos/800?random=4",
        type: "photography",
        title: "Natural Patterns 4",
        artist: "Mark Rivers",
        likes: 285,
        comments: 23,
        size: "large",
        featured: false,
    },
    {
        id: 5,
        src: "https://picsum.photos/800?random=5",
        type: "collections",
        title: "City Life 5",
        artist: "Sarah Winters",
        likes: 377,
        comments: 20,
        size: "wide",
        featured: true,
    },
    {
        id: 6,
        src: "https://picsum.photos/800?random=6",
        type: "art",
        title: "Color Theory 6",
        artist: "Ana White",
        likes: 200,
        comments: 34,
        size: "large",
        featured: false,
    },
    {
        id: 7,
        src: "https://picsum.photos/800?random=7",
        type: "photography",
        title: "Geometric Patterns 7",
        artist: "Lisa Chen",
        likes: 210,
        comments: 14,
        size: "wide",
        featured: false,
    },
    {
        id: 8,
        src: "https://picsum.photos/800?random=8",
        type: "digital",
        title: "Digital Waves 8",
        artist: "Mike Peterson",
        likes: 160,
        comments: 18,
        size: "default",
        featured: false,
    },
    {
        id: 9,
        src: "https://picsum.photos/800?random=9",
        type: "photography",
        title: "Urban Symmetry 9",
        artist: "Sarah Winters",
        likes: 275,
        comments: 20,
        size: "large",
        featured: false,
    },
    {
        id: 10,
        src: "https://picsum.photos/800?random=10",
        type: "art",
        title: "Abstract Dreams 10",
        artist: "James Lee",
        likes: 204,
        comments: 8,
        size: "tall",
        featured: true,
    },
    {
        id: 11,
        src: "https://picsum.photos/800?random=11",
        type: "digital",
        title: "Neon Nights 11",
        artist: "Elena Costa",
        likes: 235,
        comments: 22,
        size: "tall",
        featured: false,
    },
    {
        id: 12,
        src: "https://picsum.photos/800?random=12",
        type: "photography",
        title: "Natural Patterns 12",
        artist: "Mark Rivers",
        likes: 304,
        comments: 23,
        size: "large",
        featured: false,
    },
    {
        id: 13,
        src: "https://picsum.photos/800?random=13",
        type: "collections",
        title: "City Life 13",
        artist: "Sarah Winters",
        likes: 385,
        comments: 28,
        size: "wide",
        featured: false,
    },
    {
        id: 14,
        src: "https://picsum.photos/800?random=14",
        type: "art",
        title: "Color Theory 14",
        artist: "Ana White",
        likes: 199,
        comments: 27,
        size: "large",
        featured: false,
    },
    {
        id: 15,
        src: "https://picsum.photos/800?random=15",
        type: "photography",
        title: "Geometric Patterns 15",
        artist: "Lisa Chen",
        likes: 216,
        comments: 14,
        size: "wide",
        featured: true,
    },
    {
        id: 16,
        src: "https://picsum.photos/800?random=16",
        type: "digital",
        title: "Digital Waves 16",
        artist: "Mike Peterson",
        likes: 165,
        comments: 12,
        size: "default",
        featured: false,
    },
    {
        id: 17,
        src: "https://picsum.photos/800?random=17",
        type: "photography",
        title: "Urban Symmetry 17",
        artist: "Sarah Winters",
        likes: 270,
        comments: 21,
        size: "large",
        featured: false,
    },
    {
        id: 18,
        src: "https://picsum.photos/800?random=18",
        type: "art",
        title: "Abstract Dreams 18",
        artist: "James Lee",
        likes: 191,
        comments: 17,
        size: "tall",
        featured: false,
    },
    {
        id: 19,
        src: "https://picsum.photos/800?random=19",
        type: "digital",
        title: "Neon Nights 19",
        artist: "Elena Costa",
        likes: 225,
        comments: 18,
        size: "tall",
        featured: false,
    },
    {
        id: 20,
        src: "https://picsum.photos/800?random=20",
        type: "photography",
        title: "Natural Patterns 20",
        artist: "Mark Rivers",
        likes: 302,
        comments: 23,
        size: "large",
        featured: true,
    },
    {
        id: 21,
        src: "https://picsum.photos/800?random=21",
        type: "collections",
        title: "City Life 21",
        artist: "Sarah Winters",
        likes: 380,
        comments: 22,
        size: "wide",
        featured: false,
    },
    {
        id: 22,
        src: "https://picsum.photos/800?random=22",
        type: "art",
        title: "Color Theory 22",
        artist: "Ana White",
        likes: 208,
        comments: 29,
        size: "large",
        featured: false,
    },
    {
        id: 23,
        src: "https://picsum.photos/800?random=23",
        type: "photography",
        title: "Geometric Patterns 23",
        artist: "Lisa Chen",
        likes: 205,
        comments: 15,
        size: "wide",
        featured: false,
    },
    {
        id: 24,
        src: "https://picsum.photos/800?random=24",
        type: "digital",
        title: "Digital Waves 24",
        artist: "Mike Peterson",
        likes: 176,
        comments: 15,
        size: "default",
        featured: false,
    },
    {
        id: 25,
        src: "https://picsum.photos/800?random=25",
        type: "photography",
        title: "Urban Symmetry 25",
        artist: "Sarah Winters",
        likes: 238,
        comments: 12,
        size: "large",
        featured: true,
    },
    {
        id: 26,
        src: "https://picsum.photos/800?random=26",
        type: "art",
        title: "Abstract Dreams 26",
        artist: "James Lee",
        likes: 162,
        comments: 15,
        size: "tall",
        featured: false,
    },
    {
        id: 27,
        src: "https://picsum.photos/800?random=27",
        type: "digital",
        title: "Neon Nights 27",
        artist: "Elena Costa",
        likes: 215,
        comments: 19,
        size: "tall",
        featured: false,
    },
    {
        id: 28,
        src: "https://picsum.photos/800?random=28",
        type: "photography",
        title: "Natural Patterns 28",
        artist: "Mark Rivers",
        likes: 283,
        comments: 32,
        size: "large",
        featured: false,
    },
    {
        id: 29,
        src: "https://picsum.photos/800?random=29",
        type: "collections",
        title: "City Life 29",
        artist: "Sarah Winters",
        likes: 367,
        comments: 26,
        size: "wide",
        featured: false,
    },
    {
        id: 30,
        src: "https://picsum.photos/800?random=30",
        type: "art",
        title: "Color Theory 30",
        artist: "Ana White",
        likes: 223,
        comments: 29,
        size: "large",
        featured: true,
    },
    {
        id: 31,
        src: "https://picsum.photos/800?random=31",
        type: "photography",
        title: "Geometric Patterns 31",
        artist: "Lisa Chen",
        likes: 212,
        comments: 16,
        size: "wide",
        featured: false,
    },
    {
        id: 32,
        src: "https://picsum.photos/800?random=32",
        type: "digital",
        title: "Digital Waves 32",
        artist: "Mike Peterson",
        likes: 155,
        comments: 12,
        size: "default",
        featured: false,
    },
    {
        id: 33,
        src: "https://picsum.photos/800?random=33",
        type: "photography",
        title: "Urban Symmetry 33",
        artist: "Sarah Winters",
        likes: 273,
        comments: 18,
        size: "large",
        featured: false,
    },
    {
        id: 34,
        src: "https://picsum.photos/800?random=34",
        type: "art",
        title: "Abstract Dreams 34",
        artist: "James Lee",
        likes: 164,
        comments: 12,
        size: "tall",
        featured: false,
    },
    {
        id: 35,
        src: "https://picsum.photos/800?random=35",
        type: "digital",
        title: "Neon Nights 35",
        artist: "Elena Costa",
        likes: 198,
        comments: 21,
        size: "tall",
        featured: true,
    },
    {
        id: 36,
        src: "https://picsum.photos/800?random=36",
        type: "photography",
        title: "Natural Patterns 36",
        artist: "Mark Rivers",
        likes: 292,
        comments: 24,
        size: "large",
        featured: false,
    },
    {
        id: 37,
        src: "https://picsum.photos/800?random=37",
        type: "collections",
        title: "City Life 37",
        artist: "Sarah Winters",
        likes: 359,
        comments: 22,
        size: "wide",
        featured: false,
    },
    {
        id: 38,
        src: "https://picsum.photos/800?random=38",
        type: "art",
        title: "Color Theory 38",
        artist: "Ana White",
        likes: 215,
        comments: 34,
        size: "large",
        featured: false,
    },
    {
        id: 39,
        src: "https://picsum.photos/800?random=39",
        type: "photography",
        title: "Geometric Patterns 39",
        artist: "Lisa Chen",
        likes: 199,
        comments: 16,
        size: "wide",
        featured: false,
    },
    {
        id: 40,
        src: "https://picsum.photos/800?random=40",
        type: "digital",
        title: "Digital Waves 40",
        artist: "Mike Peterson",
        likes: 178,
        comments: 16,
        size: "default",
        featured: true,
    },
    {
        id: 41,
        src: "https://picsum.photos/800?random=41",
        type: "photography",
        title: "Urban Symmetry 41",
        artist: "Sarah Winters",
        likes: 282,
        comments: 15,
        size: "large",
        featured: false,
    },
    {
        id: 42,
        src: "https://picsum.photos/800?random=42",
        type: "art",
        title: "Abstract Dreams 42",
        artist: "James Lee",
        likes: 175,
        comments: 13,
        size: "tall",
        featured: false,
    },
    {
        id: 43,
        src: "https://picsum.photos/800?random=43",
        type: "digital",
        title: "Neon Nights 43",
        artist: "Elena Costa",
        likes: 189,
        comments: 20,
        size: "tall",
        featured: false,
    },
    {
        id: 44,
        src: "https://picsum.photos/800?random=44",
        type: "photography",
        title: "Natural Patterns 44",
        artist: "Mark Rivers",
        likes: 281,
        comments: 29,
        size: "large",
        featured: false,
    },
    {
        id: 45,
        src: "https://picsum.photos/800?random=45",
        type: "collections",
        title: "City Life 45",
        artist: "Sarah Winters",
        likes: 369,
        comments: 25,
        size: "wide",
        featured: true,
    },
    {
        id: 46,
        src: "https://picsum.photos/800?random=46",
        type: "art",
        title: "Color Theory 46",
        artist: "Ana White",
        likes: 231,
        comments: 32,
        size: "large",
        featured: false,
    },
    {
        id: 47,
        src: "https://picsum.photos/800?random=47",
        type: "photography",
        title: "Geometric Patterns 47",
        artist: "Lisa Chen",
        likes: 188,
        comments: 18,
        size: "wide",
        featured: false,
    },
    {
        id: 48,
        src: "https://picsum.photos/800?random=48",
        type: "digital",
        title: "Digital Waves 48",
        artist: "Mike Peterson",
        likes: 158,
        comments: 13,
        size: "default",
        featured: false,
    },
    {
        id: 49,
        src: "https://picsum.photos/800?random=49",
        type: "photography",
        title: "Urban Symmetry 49",
        artist: "Sarah Winters",
        likes: 242,
        comments: 20,
        size: "large",
        featured: false,
    },
    {
        id: 50,
        src: "https://picsum.photos/800?random=50",
        type: "art",
        title: "Abstract Dreams 50",
        artist: "James Lee",
        likes: 198,
        comments: 9,
        size: "tall",
        featured: true,
    },
];

export default galleryItems;
