const stories = [
    {
        id: 1,
        title: "The Silent Hours",
        excerpt:
            "In those moments between dusk and darkness, when the world grows quiet and memories surface like stars in the evening sky...",
        type: "Prose",
        date: "Winter, 2024",
        likes: 156,
        saves: 42,
        author: "Eleanor Wells",
    },
    {
        id: 2,
        title: "Leaves of Yesterday",
        excerpt:
            "Autumn leaves whisper tales of seasons past,\nTheir golden hues a testament to time,\nDancing on winds both gentle and vast,\nNature's poetry in motion sublime.",
        type: "Poetry",
        date: "Autumn, 2024",
        likes: 123,
        saves: 38,
        author: "Thomas Blake",
    },
    {
        id: 3,
        title: "Letters from the Sea",
        excerpt:
            "The lighthouse keeper's daughter found the first bottle on a Tuesday morning, its glass worn smooth by the endless tides...",
        type: "Short Story",
        date: "Spring, 2024",
        likes: 189,
        saves: 56,
        author: "Marie Laurent",
    },
    {
        id: 4,
        title: "Morning Musings",
        excerpt:
            "Dawn breaks softly over the city walls,\nPainting shadows on ancient stone,\nWhile time slowly recalls,\nMemories we've known.",
        type: "Poetry",
        date: "Winter, 2024",
        likes: 144,
        saves: 47,
        author: "Christopher Reed",
    },
    {
        id: 5,
        title: "Shadows of Tomorrow",
        excerpt:
            "Beneath the looming skyscrapers, a boy dreams of stars unseen, of places untouched by the chaos of modern life...",
        type: "Prose",
        date: "Summer, 2024",
        likes: 132,
        saves: 34,
        author: "Amelia Kent",
    },
    {
        id: 6,
        title: "Echoes in the Fog",
        excerpt:
            "A lone figure moved through the dense fog, their footsteps echoing against cobblestones worn by centuries of history...",
        type: "Short Story",
        date: "Autumn, 2024",
        likes: 203,
        saves: 63,
        author: "Nathaniel Grey",
    },
    {
        id: 7,
        title: "Rain's Serenade",
        excerpt:
            "The rain plays its soft symphony on the windowpanes,\nEach drop a note, each pause a rest,\nNature's lullaby for the weary souls...",
        type: "Poetry",
        date: "Monsoon, 2024",
        likes: 158,
        saves: 41,
        author: "Isabella Hart",
    },
    {
        id: 8,
        title: "The Keeper of Lanterns",
        excerpt:
            "Every night, as the village slept, she walked the cobbled streets, lighting the lanterns and carrying stories in her wake...",
        type: "Prose",
        date: "Winter, 2024",
        likes: 187,
        saves: 54,
        author: "Julia Marlowe",
    },
    {
        id: 9,
        title: "Fragments of Dreams",
        excerpt:
            "In the silence of the midnight hour,\nDreams unravel their mysteries,\nWhispering secrets of the soul,\nIn fleeting moments of clarity.",
        type: "Poetry",
        date: "Spring, 2024",
        likes: 125,
        saves: 39,
        author: "Edward Holloway",
    },
    {
        id: 10,
        title: "Beneath the Willow Tree",
        excerpt:
            "As children, they carved their names into the tree\u2019s bark, a promise to never forget, even as the years pulled them apart...",
        type: "Short Story",
        date: "Summer, 2024",
        likes: 195,
        saves: 58,
        author: "Sophia Clarke",
    },
    {
        id: 11,
        title: "Songs of the Wild",
        excerpt:
            "Deep in the heart of the forest, where sunlight barely touched the earth, the call of the wild sang in untamed harmony...",
        type: "Prose",
        date: "Autumn, 2024",
        likes: 145,
        saves: 46,
        author: "Oliver Grant",
    },
    {
        id: 12,
        title: "Frost's Embrace",
        excerpt:
            "Winter wraps the world in its icy arms,\nA fleeting hush before spring's rebirth,\nIn its cold beauty, it charms,\nThe sleeping earth.",
        type: "Poetry",
        date: "Winter, 2024",
        likes: 139,
        saves: 37,
        author: "Lydia Vaughn",
    },
    {
        id: 13,
        title: "The Clockmaker's Secret",
        excerpt:
            "In the quiet of his workshop, surrounded by ticking timepieces, the clockmaker worked tirelessly, guarding a secret older than time...",
        type: "Short Story",
        date: "Spring, 2024",
        likes: 211,
        saves: 68,
        author: "Henry Adler",
    },
    {
        id: 14,
        title: "Threads of Gold",
        excerpt:
            "In the bustling marketplace, amidst the chaos of voices and colors, she wove tales of ancient legends with threads of gold...",
        type: "Prose",
        date: "Summer, 2024",
        likes: 172,
        saves: 49,
        author: "Annabelle Frost",
    },
    {
        id: 15,
        title: "Reflections at Dusk",
        excerpt:
            "As the sun dipped below the horizon, its final rays caught the edge of the lake, turning its surface into molten gold...",
        type: "Prose",
        date: "Autumn, 2024",
        likes: 167,
        saves: 43,
        author: "Samuel Beckett",
    },
    {
        id: 16,
        title: "Whispers of the Wind",
        excerpt:
            "The wind carried stories of distant lands, its whispers echoing through the valleys and filling the night with mystery...",
        type: "Poetry",
        date: "Spring, 2024",
        likes: 133,
        saves: 44,
        author: "Fiona Harper",
    },
    {
        id: 17,
        title: "The Silent Hours",
        excerpt:
            "In those moments between dusk and darkness, when the world grows quiet and memories surface like stars in the evening sky...",
        type: "Prose",
        date: "Winter, 2024",
        likes: 156,
        saves: 42,
        author: "Eleanor Wells",
    },
    {
        id: 18,
        title: "Leaves of Yesterday",
        excerpt:
            "Autumn leaves whisper tales of seasons past,\nTheir golden hues a testament to time,\nDancing on winds both gentle and vast,\nNature's poetry in motion sublime.",
        type: "Poetry",
        date: "Autumn, 2024",
        likes: 123,
        saves: 38,
        author: "Thomas Blake",
    },
    {
        id: 19,
        title: "Letters from the Sea",
        excerpt:
            "The lighthouse keeper's daughter found the first bottle on a Tuesday morning, its glass worn smooth by the endless tides...",
        type: "Short Story",
        date: "Spring, 2024",
        likes: 189,
        saves: 56,
        author: "Marie Laurent",
    },
    {
        id: 20,
        title: "Morning Musings",
        excerpt:
            "Dawn breaks softly over the city walls,\nPainting shadows on ancient stone,\nWhile time slowly recalls,\nMemories we've known.",
        type: "Poetry",
        date: "Winter, 2024",
        likes: 144,
        saves: 47,
        author: "Christopher Reed",
    },
    {
        id: 21,
        title: "Shadows of Tomorrow",
        excerpt:
            "Beneath the looming skyscrapers, a boy dreams of stars unseen, of places untouched by the chaos of modern life...",
        type: "Prose",
        date: "Summer, 2024",
        likes: 132,
        saves: 34,
        author: "Amelia Kent",
    },
    {
        id: 22,
        title: "Echoes in the Fog",
        excerpt:
            "A lone figure moved through the dense fog, their footsteps echoing against cobblestones worn by centuries of history...",
        type: "Short Story",
        date: "Autumn, 2024",
        likes: 203,
        saves: 63,
        author: "Nathaniel Grey",
    },
    {
        id: 23,
        title: "Rain's Serenade",
        excerpt:
            "The rain plays its soft symphony on the windowpanes,\nEach drop a note, each pause a rest,\nNature's lullaby for the weary souls...",
        type: "Poetry",
        date: "Monsoon, 2024",
        likes: 158,
        saves: 41,
        author: "Isabella Hart",
    },
    {
        id: 24,
        title: "The Keeper of Lanterns",
        excerpt:
            "Every night, as the village slept, she walked the cobbled streets, lighting the lanterns and carrying stories in her wake...",
        type: "Prose",
        date: "Winter, 2024",
        likes: 187,
        saves: 54,
        author: "Julia Marlowe",
    },
    {
        id: 25,
        title: "Fragments of Dreams",
        excerpt:
            "In the silence of the midnight hour,\nDreams unravel their mysteries,\nWhispering secrets of the soul,\nIn fleeting moments of clarity.",
        type: "Poetry",
        date: "Spring, 2024",
        likes: 125,
        saves: 39,
        author: "Edward Holloway",
    },
    {
        id: 26,
        title: "Beneath the Willow Tree",
        excerpt:
            "As children, they carved their names into the tree\u2019s bark, a promise to never forget, even as the years pulled them apart...",
        type: "Short Story",
        date: "Summer, 2024",
        likes: 195,
        saves: 58,
        author: "Sophia Clarke",
    },
    {
        id: 27,
        title: "Songs of the Wild",
        excerpt:
            "Deep in the heart of the forest, where sunlight barely touched the earth, the call of the wild sang in untamed harmony...",
        type: "Prose",
        date: "Autumn, 2024",
        likes: 145,
        saves: 46,
        author: "Oliver Grant",
    },
    {
        id: 28,
        title: "Frost's Embrace",
        excerpt:
            "Winter wraps the world in its icy arms,\nA fleeting hush before spring's rebirth,\nIn its cold beauty, it charms,\nThe sleeping earth.",
        type: "Poetry",
        date: "Winter, 2024",
        likes: 139,
        saves: 37,
        author: "Lydia Vaughn",
    },
    {
        id: 29,
        title: "The Clockmaker's Secret",
        excerpt:
            "In the quiet of his workshop, surrounded by ticking timepieces, the clockmaker worked tirelessly, guarding a secret older than time...",
        type: "Short Story",
        date: "Spring, 2024",
        likes: 211,
        saves: 68,
        author: "Henry Adler",
    },
    {
        id: 30,
        title: "Threads of Gold",
        excerpt:
            "In the bustling marketplace, amidst the chaos of voices and colors, she wove tales of ancient legends with threads of gold...",
        type: "Prose",
        date: "Summer, 2024",
        likes: 172,
        saves: 49,
        author: "Annabelle Frost",
    },
    {
        id: 31,
        title: "Reflections at Dusk",
        excerpt:
            "As the sun dipped below the horizon, its final rays caught the edge of the lake, turning its surface into molten gold...",
        type: "Prose",
        date: "Autumn, 2024",
        likes: 167,
        saves: 43,
        author: "Samuel Beckett",
    },
    {
        id: 32,
        title: "Whispers of the Wind",
        excerpt:
            "The wind carried stories of distant lands, its whispers echoing through the valleys and filling the night with mystery...",
        type: "Poetry",
        date: "Spring, 2024",
        likes: 133,
        saves: 44,
        author: "Fiona Harper",
    },
    {
        id: 33,
        title: "The Silent Hours",
        excerpt:
            "In those moments between dusk and darkness, when the world grows quiet and memories surface like stars in the evening sky...",
        type: "Prose",
        date: "Winter, 2024",
        likes: 156,
        saves: 42,
        author: "Eleanor Wells",
    },
    {
        id: 34,
        title: "Leaves of Yesterday",
        excerpt:
            "Autumn leaves whisper tales of seasons past,\nTheir golden hues a testament to time,\nDancing on winds both gentle and vast,\nNature's poetry in motion sublime.",
        type: "Poetry",
        date: "Autumn, 2024",
        likes: 123,
        saves: 38,
        author: "Thomas Blake",
    },
    {
        id: 35,
        title: "Letters from the Sea",
        excerpt:
            "The lighthouse keeper's daughter found the first bottle on a Tuesday morning, its glass worn smooth by the endless tides...",
        type: "Short Story",
        date: "Spring, 2024",
        likes: 189,
        saves: 56,
        author: "Marie Laurent",
    },
    {
        id: 36,
        title: "Morning Musings",
        excerpt:
            "Dawn breaks softly over the city walls,\nPainting shadows on ancient stone,\nWhile time slowly recalls,\nMemories we've known.",
        type: "Poetry",
        date: "Winter, 2024",
        likes: 144,
        saves: 47,
        author: "Christopher Reed",
    },
    {
        id: 37,
        title: "Shadows of Tomorrow",
        excerpt:
            "Beneath the looming skyscrapers, a boy dreams of stars unseen, of places untouched by the chaos of modern life...",
        type: "Prose",
        date: "Summer, 2024",
        likes: 132,
        saves: 34,
        author: "Amelia Kent",
    },
    {
        id: 38,
        title: "Echoes in the Fog",
        excerpt:
            "A lone figure moved through the dense fog, their footsteps echoing against cobblestones worn by centuries of history...",
        type: "Short Story",
        date: "Autumn, 2024",
        likes: 203,
        saves: 63,
        author: "Nathaniel Grey",
    },
    {
        id: 39,
        title: "Rain's Serenade",
        excerpt:
            "The rain plays its soft symphony on the windowpanes,\nEach drop a note, each pause a rest,\nNature's lullaby for the weary souls...",
        type: "Poetry",
        date: "Monsoon, 2024",
        likes: 158,
        saves: 41,
        author: "Isabella Hart",
    },
    {
        id: 40,
        title: "The Keeper of Lanterns",
        excerpt:
            "Every night, as the village slept, she walked the cobbled streets, lighting the lanterns and carrying stories in her wake...",
        type: "Prose",
        date: "Winter, 2024",
        likes: 187,
        saves: 54,
        author: "Julia Marlowe",
    },
    {
        id: 41,
        title: "Fragments of Dreams",
        excerpt:
            "In the silence of the midnight hour,\nDreams unravel their mysteries,\nWhispering secrets of the soul,\nIn fleeting moments of clarity.",
        type: "Poetry",
        date: "Spring, 2024",
        likes: 125,
        saves: 39,
        author: "Edward Holloway",
    },
    {
        id: 42,
        title: "Beneath the Willow Tree",
        excerpt:
            "As children, they carved their names into the tree\u2019s bark, a promise to never forget, even as the years pulled them apart...",
        type: "Short Story",
        date: "Summer, 2024",
        likes: 195,
        saves: 58,
        author: "Sophia Clarke",
    },
    {
        id: 43,
        title: "Songs of the Wild",
        excerpt:
            "Deep in the heart of the forest, where sunlight barely touched the earth, the call of the wild sang in untamed harmony...",
        type: "Prose",
        date: "Autumn, 2024",
        likes: 145,
        saves: 46,
        author: "Oliver Grant",
    },
    {
        id: 44,
        title: "Frost's Embrace",
        excerpt:
            "Winter wraps the world in its icy arms,\nA fleeting hush before spring's rebirth,\nIn its cold beauty, it charms,\nThe sleeping earth.",
        type: "Poetry",
        date: "Winter, 2024",
        likes: 139,
        saves: 37,
        author: "Lydia Vaughn",
    },
    {
        id: 45,
        title: "The Clockmaker's Secret",
        excerpt:
            "In the quiet of his workshop, surrounded by ticking timepieces, the clockmaker worked tirelessly, guarding a secret older than time...",
        type: "Short Story",
        date: "Spring, 2024",
        likes: 211,
        saves: 68,
        author: "Henry Adler",
    },
    {
        id: 46,
        title: "Threads of Gold",
        excerpt:
            "In the bustling marketplace, amidst the chaos of voices and colors, she wove tales of ancient legends with threads of gold...",
        type: "Prose",
        date: "Summer, 2024",
        likes: 172,
        saves: 49,
        author: "Annabelle Frost",
    },
    {
        id: 47,
        title: "Reflections at Dusk",
        excerpt:
            "As the sun dipped below the horizon, its final rays caught the edge of the lake, turning its surface into molten gold...",
        type: "Prose",
        date: "Autumn, 2024",
        likes: 167,
        saves: 43,
        author: "Samuel Beckett",
    },
    {
        id: 48,
        title: "Whispers of the Wind",
        excerpt:
            "The wind carried stories of distant lands, its whispers echoing through the valleys and filling the night with mystery...",
        type: "Poetry",
        date: "Spring, 2024",
        likes: 133,
        saves: 44,
        author: "Fiona Harper",
    },
    {
        id: 49,
        title: "The Silent Hours",
        excerpt:
            "In those moments between dusk and darkness, when the world grows quiet and memories surface like stars in the evening sky...",
        type: "Prose",
        date: "Winter, 2024",
        likes: 156,
        saves: 42,
        author: "Eleanor Wells",
    },
    {
        id: 50,
        title: "Leaves of Yesterday",
        excerpt:
            "Autumn leaves whisper tales of seasons past,\nTheir golden hues a testament to time,\nDancing on winds both gentle and vast,\nNature's poetry in motion sublime.",
        type: "Poetry",
        date: "Autumn, 2024",
        likes: 123,
        saves: 38,
        author: "Thomas Blake",
    },
    {
        id: 51,
        title: "Letters from the Sea",
        excerpt:
            "The lighthouse keeper's daughter found the first bottle on a Tuesday morning, its glass worn smooth by the endless tides...",
        type: "Short Story",
        date: "Spring, 2024",
        likes: 189,
        saves: 56,
        author: "Marie Laurent",
    },
    {
        id: 52,
        title: "Morning Musings",
        excerpt:
            "Dawn breaks softly over the city walls,\nPainting shadows on ancient stone,\nWhile time slowly recalls,\nMemories we've known.",
        type: "Poetry",
        date: "Winter, 2024",
        likes: 144,
        saves: 47,
        author: "Christopher Reed",
    },
    {
        id: 53,
        title: "Shadows of Tomorrow",
        excerpt:
            "Beneath the looming skyscrapers, a boy dreams of stars unseen, of places untouched by the chaos of modern life...",
        type: "Prose",
        date: "Summer, 2024",
        likes: 132,
        saves: 34,
        author: "Amelia Kent",
    },
    {
        id: 54,
        title: "Echoes in the Fog",
        excerpt:
            "A lone figure moved through the dense fog, their footsteps echoing against cobblestones worn by centuries of history...",
        type: "Short Story",
        date: "Autumn, 2024",
        likes: 203,
        saves: 63,
        author: "Nathaniel Grey",
    },
    {
        id: 55,
        title: "Rain's Serenade",
        excerpt:
            "The rain plays its soft symphony on the windowpanes,\nEach drop a note, each pause a rest,\nNature's lullaby for the weary souls...",
        type: "Poetry",
        date: "Monsoon, 2024",
        likes: 158,
        saves: 41,
        author: "Isabella Hart",
    },
    {
        id: 56,
        title: "The Keeper of Lanterns",
        excerpt:
            "Every night, as the village slept, she walked the cobbled streets, lighting the lanterns and carrying stories in her wake...",
        type: "Prose",
        date: "Winter, 2024",
        likes: 187,
        saves: 54,
        author: "Julia Marlowe",
    },
    {
        id: 57,
        title: "Fragments of Dreams",
        excerpt:
            "In the silence of the midnight hour,\nDreams unravel their mysteries,\nWhispering secrets of the soul,\nIn fleeting moments of clarity.",
        type: "Poetry",
        date: "Spring, 2024",
        likes: 125,
        saves: 39,
        author: "Edward Holloway",
    },
    {
        id: 58,
        title: "Beneath the Willow Tree",
        excerpt:
            "As children, they carved their names into the tree\u2019s bark, a promise to never forget, even as the years pulled them apart...",
        type: "Short Story",
        date: "Summer, 2024",
        likes: 195,
        saves: 58,
        author: "Sophia Clarke",
    },
    {
        id: 59,
        title: "Songs of the Wild",
        excerpt:
            "Deep in the heart of the forest, where sunlight barely touched the earth, the call of the wild sang in untamed harmony...",
        type: "Prose",
        date: "Autumn, 2024",
        likes: 145,
        saves: 46,
        author: "Oliver Grant",
    },
    {
        id: 60,
        title: "Frost's Embrace",
        excerpt:
            "Winter wraps the world in its icy arms,\nA fleeting hush before spring's rebirth,\nIn its cold beauty, it charms,\nThe sleeping earth.",
        type: "Poetry",
        date: "Winter, 2024",
        likes: 139,
        saves: 37,
        author: "Lydia Vaughn",
    },
    {
        id: 61,
        title: "The Clockmaker's Secret",
        excerpt:
            "In the quiet of his workshop, surrounded by ticking timepieces, the clockmaker worked tirelessly, guarding a secret older than time...",
        type: "Short Story",
        date: "Spring, 2024",
        likes: 211,
        saves: 68,
        author: "Henry Adler",
    },
    {
        id: 62,
        title: "Threads of Gold",
        excerpt:
            "In the bustling marketplace, amidst the chaos of voices and colors, she wove tales of ancient legends with threads of gold...",
        type: "Prose",
        date: "Summer, 2024",
        likes: 172,
        saves: 49,
        author: "Annabelle Frost",
    },
    {
        id: 63,
        title: "Reflections at Dusk",
        excerpt:
            "As the sun dipped below the horizon, its final rays caught the edge of the lake, turning its surface into molten gold...",
        type: "Prose",
        date: "Autumn, 2024",
        likes: 167,
        saves: 43,
        author: "Samuel Beckett",
    },
    {
        id: 64,
        title: "Whispers of the Wind",
        excerpt:
            "The wind carried stories of distant lands, its whispers echoing through the valleys and filling the night with mystery...",
        type: "Poetry",
        date: "Spring, 2024",
        likes: 133,
        saves: 44,
        author: "Fiona Harper",
    },
    {
        id: 65,
        title: "The Silent Hours",
        excerpt:
            "In those moments between dusk and darkness, when the world grows quiet and memories surface like stars in the evening sky...",
        type: "Prose",
        date: "Winter, 2024",
        likes: 156,
        saves: 42,
        author: "Eleanor Wells",
    },
    {
        id: 66,
        title: "Leaves of Yesterday",
        excerpt:
            "Autumn leaves whisper tales of seasons past,\nTheir golden hues a testament to time,\nDancing on winds both gentle and vast,\nNature's poetry in motion sublime.",
        type: "Poetry",
        date: "Autumn, 2024",
        likes: 123,
        saves: 38,
        author: "Thomas Blake",
    },
    {
        id: 67,
        title: "Letters from the Sea",
        excerpt:
            "The lighthouse keeper's daughter found the first bottle on a Tuesday morning, its glass worn smooth by the endless tides...",
        type: "Short Story",
        date: "Spring, 2024",
        likes: 189,
        saves: 56,
        author: "Marie Laurent",
    },
    {
        id: 68,
        title: "Morning Musings",
        excerpt:
            "Dawn breaks softly over the city walls,\nPainting shadows on ancient stone,\nWhile time slowly recalls,\nMemories we've known.",
        type: "Poetry",
        date: "Winter, 2024",
        likes: 144,
        saves: 47,
        author: "Christopher Reed",
    },
    {
        id: 69,
        title: "Shadows of Tomorrow",
        excerpt:
            "Beneath the looming skyscrapers, a boy dreams of stars unseen, of places untouched by the chaos of modern life...",
        type: "Prose",
        date: "Summer, 2024",
        likes: 132,
        saves: 34,
        author: "Amelia Kent",
    },
    {
        id: 70,
        title: "Echoes in the Fog",
        excerpt:
            "A lone figure moved through the dense fog, their footsteps echoing against cobblestones worn by centuries of history...",
        type: "Short Story",
        date: "Autumn, 2024",
        likes: 203,
        saves: 63,
        author: "Nathaniel Grey",
    },
    {
        id: 71,
        title: "Rain's Serenade",
        excerpt:
            "The rain plays its soft symphony on the windowpanes,\nEach drop a note, each pause a rest,\nNature's lullaby for the weary souls...",
        type: "Poetry",
        date: "Monsoon, 2024",
        likes: 158,
        saves: 41,
        author: "Isabella Hart",
    },
    {
        id: 72,
        title: "The Keeper of Lanterns",
        excerpt:
            "Every night, as the village slept, she walked the cobbled streets, lighting the lanterns and carrying stories in her wake...",
        type: "Prose",
        date: "Winter, 2024",
        likes: 187,
        saves: 54,
        author: "Julia Marlowe",
    },
    {
        id: 73,
        title: "Fragments of Dreams",
        excerpt:
            "In the silence of the midnight hour,\nDreams unravel their mysteries,\nWhispering secrets of the soul,\nIn fleeting moments of clarity.",
        type: "Poetry",
        date: "Spring, 2024",
        likes: 125,
        saves: 39,
        author: "Edward Holloway",
    },
    {
        id: 74,
        title: "Beneath the Willow Tree",
        excerpt:
            "As children, they carved their names into the tree\u2019s bark, a promise to never forget, even as the years pulled them apart...",
        type: "Short Story",
        date: "Summer, 2024",
        likes: 195,
        saves: 58,
        author: "Sophia Clarke",
    },
    {
        id: 75,
        title: "Songs of the Wild",
        excerpt:
            "Deep in the heart of the forest, where sunlight barely touched the earth, the call of the wild sang in untamed harmony...",
        type: "Prose",
        date: "Autumn, 2024",
        likes: 145,
        saves: 46,
        author: "Oliver Grant",
    },
    {
        id: 76,
        title: "Frost's Embrace",
        excerpt:
            "Winter wraps the world in its icy arms,\nA fleeting hush before spring's rebirth,\nIn its cold beauty, it charms,\nThe sleeping earth.",
        type: "Poetry",
        date: "Winter, 2024",
        likes: 139,
        saves: 37,
        author: "Lydia Vaughn",
    },
    {
        id: 77,
        title: "The Clockmaker's Secret",
        excerpt:
            "In the quiet of his workshop, surrounded by ticking timepieces, the clockmaker worked tirelessly, guarding a secret older than time...",
        type: "Short Story",
        date: "Spring, 2024",
        likes: 211,
        saves: 68,
        author: "Henry Adler",
    },
    {
        id: 78,
        title: "Threads of Gold",
        excerpt:
            "In the bustling marketplace, amidst the chaos of voices and colors, she wove tales of ancient legends with threads of gold...",
        type: "Prose",
        date: "Summer, 2024",
        likes: 172,
        saves: 49,
        author: "Annabelle Frost",
    },
    {
        id: 79,
        title: "Reflections at Dusk",
        excerpt:
            "As the sun dipped below the horizon, its final rays caught the edge of the lake, turning its surface into molten gold...",
        type: "Prose",
        date: "Autumn, 2024",
        likes: 167,
        saves: 43,
        author: "Samuel Beckett",
    },
    {
        id: 80,
        title: "Whispers of the Wind",
        excerpt:
            "The wind carried stories of distant lands, its whispers echoing through the valleys and filling the night with mystery...",
        type: "Poetry",
        date: "Spring, 2024",
        likes: 133,
        saves: 44,
        author: "Fiona Harper",
    },
    {
        id: 81,
        title: "The Silent Hours",
        excerpt:
            "In those moments between dusk and darkness, when the world grows quiet and memories surface like stars in the evening sky...",
        type: "Prose",
        date: "Winter, 2024",
        likes: 156,
        saves: 42,
        author: "Eleanor Wells",
    },
    {
        id: 82,
        title: "Leaves of Yesterday",
        excerpt:
            "Autumn leaves whisper tales of seasons past,\nTheir golden hues a testament to time,\nDancing on winds both gentle and vast,\nNature's poetry in motion sublime.",
        type: "Poetry",
        date: "Autumn, 2024",
        likes: 123,
        saves: 38,
        author: "Thomas Blake",
    },
    {
        id: 83,
        title: "Letters from the Sea",
        excerpt:
            "The lighthouse keeper's daughter found the first bottle on a Tuesday morning, its glass worn smooth by the endless tides...",
        type: "Short Story",
        date: "Spring, 2024",
        likes: 189,
        saves: 56,
        author: "Marie Laurent",
    },
    {
        id: 84,
        title: "Morning Musings",
        excerpt:
            "Dawn breaks softly over the city walls,\nPainting shadows on ancient stone,\nWhile time slowly recalls,\nMemories we've known.",
        type: "Poetry",
        date: "Winter, 2024",
        likes: 144,
        saves: 47,
        author: "Christopher Reed",
    },
    {
        id: 85,
        title: "Shadows of Tomorrow",
        excerpt:
            "Beneath the looming skyscrapers, a boy dreams of stars unseen, of places untouched by the chaos of modern life...",
        type: "Prose",
        date: "Summer, 2024",
        likes: 132,
        saves: 34,
        author: "Amelia Kent",
    },
    {
        id: 86,
        title: "Echoes in the Fog",
        excerpt:
            "A lone figure moved through the dense fog, their footsteps echoing against cobblestones worn by centuries of history...",
        type: "Short Story",
        date: "Autumn, 2024",
        likes: 203,
        saves: 63,
        author: "Nathaniel Grey",
    },
    {
        id: 87,
        title: "Rain's Serenade",
        excerpt:
            "The rain plays its soft symphony on the windowpanes,\nEach drop a note, each pause a rest,\nNature's lullaby for the weary souls...",
        type: "Poetry",
        date: "Monsoon, 2024",
        likes: 158,
        saves: 41,
        author: "Isabella Hart",
    },
    {
        id: 88,
        title: "The Keeper of Lanterns",
        excerpt:
            "Every night, as the village slept, she walked the cobbled streets, lighting the lanterns and carrying stories in her wake...",
        type: "Prose",
        date: "Winter, 2024",
        likes: 187,
        saves: 54,
        author: "Julia Marlowe",
    },
    {
        id: 89,
        title: "Fragments of Dreams",
        excerpt:
            "In the silence of the midnight hour,\nDreams unravel their mysteries,\nWhispering secrets of the soul,\nIn fleeting moments of clarity.",
        type: "Poetry",
        date: "Spring, 2024",
        likes: 125,
        saves: 39,
        author: "Edward Holloway",
    },
    {
        id: 90,
        title: "Beneath the Willow Tree",
        excerpt:
            "As children, they carved their names into the tree\u2019s bark, a promise to never forget, even as the years pulled them apart...",
        type: "Short Story",
        date: "Summer, 2024",
        likes: 195,
        saves: 58,
        author: "Sophia Clarke",
    },
    {
        id: 91,
        title: "Songs of the Wild",
        excerpt:
            "Deep in the heart of the forest, where sunlight barely touched the earth, the call of the wild sang in untamed harmony...",
        type: "Prose",
        date: "Autumn, 2024",
        likes: 145,
        saves: 46,
        author: "Oliver Grant",
    },
    {
        id: 92,
        title: "Frost's Embrace",
        excerpt:
            "Winter wraps the world in its icy arms,\nA fleeting hush before spring's rebirth,\nIn its cold beauty, it charms,\nThe sleeping earth.",
        type: "Poetry",
        date: "Winter, 2024",
        likes: 139,
        saves: 37,
        author: "Lydia Vaughn",
    },
    {
        id: 93,
        title: "The Clockmaker's Secret",
        excerpt:
            "In the quiet of his workshop, surrounded by ticking timepieces, the clockmaker worked tirelessly, guarding a secret older than time...",
        type: "Short Story",
        date: "Spring, 2024",
        likes: 211,
        saves: 68,
        author: "Henry Adler",
    },
    {
        id: 94,
        title: "Threads of Gold",
        excerpt:
            "In the bustling marketplace, amidst the chaos of voices and colors, she wove tales of ancient legends with threads of gold...",
        type: "Prose",
        date: "Summer, 2024",
        likes: 172,
        saves: 49,
        author: "Annabelle Frost",
    },
    {
        id: 95,
        title: "Reflections at Dusk",
        excerpt:
            "As the sun dipped below the horizon, its final rays caught the edge of the lake, turning its surface into molten gold...",
        type: "Prose",
        date: "Autumn, 2024",
        likes: 167,
        saves: 43,
        author: "Samuel Beckett",
    },
    {
        id: 96,
        title: "Whispers of the Wind",
        excerpt:
            "The wind carried stories of distant lands, its whispers echoing through the valleys and filling the night with mystery...",
        type: "Poetry",
        date: "Spring, 2024",
        likes: 133,
        saves: 44,
        author: "Fiona Harper",
    },
    {
        id: 97,
        title: "The Silent Hours",
        excerpt:
            "In those moments between dusk and darkness, when the world grows quiet and memories surface like stars in the evening sky...",
        type: "Prose",
        date: "Winter, 2024",
        likes: 156,
        saves: 42,
        author: "Eleanor Wells",
    },
    {
        id: 98,
        title: "Leaves of Yesterday",
        excerpt:
            "Autumn leaves whisper tales of seasons past,\nTheir golden hues a testament to time,\nDancing on winds both gentle and vast,\nNature's poetry in motion sublime.",
        type: "Poetry",
        date: "Autumn, 2024",
        likes: 123,
        saves: 38,
        author: "Thomas Blake",
    },
    {
        id: 99,
        title: "Letters from the Sea",
        excerpt:
            "The lighthouse keeper's daughter found the first bottle on a Tuesday morning, its glass worn smooth by the endless tides...",
        type: "Short Story",
        date: "Spring, 2024",
        likes: 189,
        saves: 56,
        author: "Marie Laurent",
    },
    {
        id: 100,
        title: "Morning Musings",
        excerpt:
            "Dawn breaks softly over the city walls,\nPainting shadows on ancient stone,\nWhile time slowly recalls,\nMemories we've known.",
        type: "Poetry",
        date: "Winter, 2024",
        likes: 144,
        saves: 47,
        author: "Christopher Reed",
    },
    {
        id: 101,
        title: "Shadows of Tomorrow",
        excerpt:
            "Beneath the looming skyscrapers, a boy dreams of stars unseen, of places untouched by the chaos of modern life...",
        type: "Prose",
        date: "Summer, 2024",
        likes: 132,
        saves: 34,
        author: "Amelia Kent",
    },
    {
        id: 102,
        title: "Echoes in the Fog",
        excerpt:
            "A lone figure moved through the dense fog, their footsteps echoing against cobblestones worn by centuries of history...",
        type: "Short Story",
        date: "Autumn, 2024",
        likes: 203,
        saves: 63,
        author: "Nathaniel Grey",
    },
    {
        id: 103,
        title: "Rain's Serenade",
        excerpt:
            "The rain plays its soft symphony on the windowpanes,\nEach drop a note, each pause a rest,\nNature's lullaby for the weary souls...",
        type: "Poetry",
        date: "Monsoon, 2024",
        likes: 158,
        saves: 41,
        author: "Isabella Hart",
    },
    {
        id: 104,
        title: "The Keeper of Lanterns",
        excerpt:
            "Every night, as the village slept, she walked the cobbled streets, lighting the lanterns and carrying stories in her wake...",
        type: "Prose",
        date: "Winter, 2024",
        likes: 187,
        saves: 54,
        author: "Julia Marlowe",
    },
    {
        id: 105,
        title: "Fragments of Dreams",
        excerpt:
            "In the silence of the midnight hour,\nDreams unravel their mysteries,\nWhispering secrets of the soul,\nIn fleeting moments of clarity.",
        type: "Poetry",
        date: "Spring, 2024",
        likes: 125,
        saves: 39,
        author: "Edward Holloway",
    },
    {
        id: 106,
        title: "Beneath the Willow Tree",
        excerpt:
            "As children, they carved their names into the tree\u2019s bark, a promise to never forget, even as the years pulled them apart...",
        type: "Short Story",
        date: "Summer, 2024",
        likes: 195,
        saves: 58,
        author: "Sophia Clarke",
    },
    {
        id: 107,
        title: "Songs of the Wild",
        excerpt:
            "Deep in the heart of the forest, where sunlight barely touched the earth, the call of the wild sang in untamed harmony...",
        type: "Prose",
        date: "Autumn, 2024",
        likes: 145,
        saves: 46,
        author: "Oliver Grant",
    },
    {
        id: 108,
        title: "Frost's Embrace",
        excerpt:
            "Winter wraps the world in its icy arms,\nA fleeting hush before spring's rebirth,\nIn its cold beauty, it charms,\nThe sleeping earth.",
        type: "Poetry",
        date: "Winter, 2024",
        likes: 139,
        saves: 37,
        author: "Lydia Vaughn",
    },
    {
        id: 109,
        title: "The Clockmaker's Secret",
        excerpt:
            "In the quiet of his workshop, surrounded by ticking timepieces, the clockmaker worked tirelessly, guarding a secret older than time...",
        type: "Short Story",
        date: "Spring, 2024",
        likes: 211,
        saves: 68,
        author: "Henry Adler",
    },
    {
        id: 110,
        title: "Threads of Gold",
        excerpt:
            "In the bustling marketplace, amidst the chaos of voices and colors, she wove tales of ancient legends with threads of gold...",
        type: "Prose",
        date: "Summer, 2024",
        likes: 172,
        saves: 49,
        author: "Annabelle Frost",
    },
    {
        id: 111,
        title: "Reflections at Dusk",
        excerpt:
            "As the sun dipped below the horizon, its final rays caught the edge of the lake, turning its surface into molten gold...",
        type: "Prose",
        date: "Autumn, 2024",
        likes: 167,
        saves: 43,
        author: "Samuel Beckett",
    },
    {
        id: 112,
        title: "Whispers of the Wind",
        excerpt:
            "The wind carried stories of distant lands, its whispers echoing through the valleys and filling the night with mystery...",
        type: "Poetry",
        date: "Spring, 2024",
        likes: 133,
        saves: 44,
        author: "Fiona Harper",
    },
    {
        id: 113,
        title: "The Silent Hours",
        excerpt:
            "In those moments between dusk and darkness, when the world grows quiet and memories surface like stars in the evening sky...",
        type: "Prose",
        date: "Winter, 2024",
        likes: 156,
        saves: 42,
        author: "Eleanor Wells",
    },
    {
        id: 114,
        title: "Leaves of Yesterday",
        excerpt:
            "Autumn leaves whisper tales of seasons past,\nTheir golden hues a testament to time,\nDancing on winds both gentle and vast,\nNature's poetry in motion sublime.",
        type: "Poetry",
        date: "Autumn, 2024",
        likes: 123,
        saves: 38,
        author: "Thomas Blake",
    },
    {
        id: 115,
        title: "Letters from the Sea",
        excerpt:
            "The lighthouse keeper's daughter found the first bottle on a Tuesday morning, its glass worn smooth by the endless tides...",
        type: "Short Story",
        date: "Spring, 2024",
        likes: 189,
        saves: 56,
        author: "Marie Laurent",
    },
    {
        id: 116,
        title: "Morning Musings",
        excerpt:
            "Dawn breaks softly over the city walls,\nPainting shadows on ancient stone,\nWhile time slowly recalls,\nMemories we've known.",
        type: "Poetry",
        date: "Winter, 2024",
        likes: 144,
        saves: 47,
        author: "Christopher Reed",
    },
    {
        id: 117,
        title: "Shadows of Tomorrow",
        excerpt:
            "Beneath the looming skyscrapers, a boy dreams of stars unseen, of places untouched by the chaos of modern life...",
        type: "Prose",
        date: "Summer, 2024",
        likes: 132,
        saves: 34,
        author: "Amelia Kent",
    },
    {
        id: 118,
        title: "Echoes in the Fog",
        excerpt:
            "A lone figure moved through the dense fog, their footsteps echoing against cobblestones worn by centuries of history...",
        type: "Short Story",
        date: "Autumn, 2024",
        likes: 203,
        saves: 63,
        author: "Nathaniel Grey",
    },
    {
        id: 119,
        title: "Rain's Serenade",
        excerpt:
            "The rain plays its soft symphony on the windowpanes,\nEach drop a note, each pause a rest,\nNature's lullaby for the weary souls...",
        type: "Poetry",
        date: "Monsoon, 2024",
        likes: 158,
        saves: 41,
        author: "Isabella Hart",
    },
    {
        id: 120,
        title: "The Keeper of Lanterns",
        excerpt:
            "Every night, as the village slept, she walked the cobbled streets, lighting the lanterns and carrying stories in her wake...",
        type: "Prose",
        date: "Winter, 2024",
        likes: 187,
        saves: 54,
        author: "Julia Marlowe",
    },
    {
        id: 121,
        title: "Fragments of Dreams",
        excerpt:
            "In the silence of the midnight hour,\nDreams unravel their mysteries,\nWhispering secrets of the soul,\nIn fleeting moments of clarity.",
        type: "Poetry",
        date: "Spring, 2024",
        likes: 125,
        saves: 39,
        author: "Edward Holloway",
    },
    {
        id: 122,
        title: "Beneath the Willow Tree",
        excerpt:
            "As children, they carved their names into the tree\u2019s bark, a promise to never forget, even as the years pulled them apart...",
        type: "Short Story",
        date: "Summer, 2024",
        likes: 195,
        saves: 58,
        author: "Sophia Clarke",
    },
    {
        id: 123,
        title: "Songs of the Wild",
        excerpt:
            "Deep in the heart of the forest, where sunlight barely touched the earth, the call of the wild sang in untamed harmony...",
        type: "Prose",
        date: "Autumn, 2024",
        likes: 145,
        saves: 46,
        author: "Oliver Grant",
    },
    {
        id: 124,
        title: "Frost's Embrace",
        excerpt:
            "Winter wraps the world in its icy arms,\nA fleeting hush before spring's rebirth,\nIn its cold beauty, it charms,\nThe sleeping earth.",
        type: "Poetry",
        date: "Winter, 2024",
        likes: 139,
        saves: 37,
        author: "Lydia Vaughn",
    },
    {
        id: 125,
        title: "The Clockmaker's Secret",
        excerpt:
            "In the quiet of his workshop, surrounded by ticking timepieces, the clockmaker worked tirelessly, guarding a secret older than time...",
        type: "Short Story",
        date: "Spring, 2024",
        likes: 211,
        saves: 68,
        author: "Henry Adler",
    },
    {
        id: 126,
        title: "Threads of Gold",
        excerpt:
            "In the bustling marketplace, amidst the chaos of voices and colors, she wove tales of ancient legends with threads of gold...",
        type: "Prose",
        date: "Summer, 2024",
        likes: 172,
        saves: 49,
        author: "Annabelle Frost",
    },
    {
        id: 127,
        title: "Reflections at Dusk",
        excerpt:
            "As the sun dipped below the horizon, its final rays caught the edge of the lake, turning its surface into molten gold...",
        type: "Prose",
        date: "Autumn, 2024",
        likes: 167,
        saves: 43,
        author: "Samuel Beckett",
    },
    {
        id: 128,
        title: "Whispers of the Wind",
        excerpt:
            "The wind carried stories of distant lands, its whispers echoing through the valleys and filling the night with mystery...",
        type: "Poetry",
        date: "Spring, 2024",
        likes: 133,
        saves: 44,
        author: "Fiona Harper",
    },
    {
        id: 129,
        title: "The Silent Hours",
        excerpt:
            "In those moments between dusk and darkness, when the world grows quiet and memories surface like stars in the evening sky...",
        type: "Prose",
        date: "Winter, 2024",
        likes: 156,
        saves: 42,
        author: "Eleanor Wells",
    },
    {
        id: 130,
        title: "Leaves of Yesterday",
        excerpt:
            "Autumn leaves whisper tales of seasons past,\nTheir golden hues a testament to time,\nDancing on winds both gentle and vast,\nNature's poetry in motion sublime.",
        type: "Poetry",
        date: "Autumn, 2024",
        likes: 123,
        saves: 38,
        author: "Thomas Blake",
    },
    {
        id: 131,
        title: "Letters from the Sea",
        excerpt:
            "The lighthouse keeper's daughter found the first bottle on a Tuesday morning, its glass worn smooth by the endless tides...",
        type: "Short Story",
        date: "Spring, 2024",
        likes: 189,
        saves: 56,
        author: "Marie Laurent",
    },
    {
        id: 132,
        title: "Morning Musings",
        excerpt:
            "Dawn breaks softly over the city walls,\nPainting shadows on ancient stone,\nWhile time slowly recalls,\nMemories we've known.",
        type: "Poetry",
        date: "Winter, 2024",
        likes: 144,
        saves: 47,
        author: "Christopher Reed",
    },
    {
        id: 133,
        title: "Shadows of Tomorrow",
        excerpt:
            "Beneath the looming skyscrapers, a boy dreams of stars unseen, of places untouched by the chaos of modern life...",
        type: "Prose",
        date: "Summer, 2024",
        likes: 132,
        saves: 34,
        author: "Amelia Kent",
    },
    {
        id: 134,
        title: "Echoes in the Fog",
        excerpt:
            "A lone figure moved through the dense fog, their footsteps echoing against cobblestones worn by centuries of history...",
        type: "Short Story",
        date: "Autumn, 2024",
        likes: 203,
        saves: 63,
        author: "Nathaniel Grey",
    },
    {
        id: 135,
        title: "Rain's Serenade",
        excerpt:
            "The rain plays its soft symphony on the windowpanes,\nEach drop a note, each pause a rest,\nNature's lullaby for the weary souls...",
        type: "Poetry",
        date: "Monsoon, 2024",
        likes: 158,
        saves: 41,
        author: "Isabella Hart",
    },
    {
        id: 136,
        title: "The Keeper of Lanterns",
        excerpt:
            "Every night, as the village slept, she walked the cobbled streets, lighting the lanterns and carrying stories in her wake...",
        type: "Prose",
        date: "Winter, 2024",
        likes: 187,
        saves: 54,
        author: "Julia Marlowe",
    },
    {
        id: 137,
        title: "Fragments of Dreams",
        excerpt:
            "In the silence of the midnight hour,\nDreams unravel their mysteries,\nWhispering secrets of the soul,\nIn fleeting moments of clarity.",
        type: "Poetry",
        date: "Spring, 2024",
        likes: 125,
        saves: 39,
        author: "Edward Holloway",
    },
    {
        id: 138,
        title: "Beneath the Willow Tree",
        excerpt:
            "As children, they carved their names into the tree\u2019s bark, a promise to never forget, even as the years pulled them apart...",
        type: "Short Story",
        date: "Summer, 2024",
        likes: 195,
        saves: 58,
        author: "Sophia Clarke",
    },
    {
        id: 139,
        title: "Songs of the Wild",
        excerpt:
            "Deep in the heart of the forest, where sunlight barely touched the earth, the call of the wild sang in untamed harmony...",
        type: "Prose",
        date: "Autumn, 2024",
        likes: 145,
        saves: 46,
        author: "Oliver Grant",
    },
    {
        id: 140,
        title: "Frost's Embrace",
        excerpt:
            "Winter wraps the world in its icy arms,\nA fleeting hush before spring's rebirth,\nIn its cold beauty, it charms,\nThe sleeping earth.",
        type: "Poetry",
        date: "Winter, 2024",
        likes: 139,
        saves: 37,
        author: "Lydia Vaughn",
    },
    {
        id: 141,
        title: "The Clockmaker's Secret",
        excerpt:
            "In the quiet of his workshop, surrounded by ticking timepieces, the clockmaker worked tirelessly, guarding a secret older than time...",
        type: "Short Story",
        date: "Spring, 2024",
        likes: 211,
        saves: 68,
        author: "Henry Adler",
    },
    {
        id: 142,
        title: "Threads of Gold",
        excerpt:
            "In the bustling marketplace, amidst the chaos of voices and colors, she wove tales of ancient legends with threads of gold...",
        type: "Prose",
        date: "Summer, 2024",
        likes: 172,
        saves: 49,
        author: "Annabelle Frost",
    },
    {
        id: 143,
        title: "Reflections at Dusk",
        excerpt:
            "As the sun dipped below the horizon, its final rays caught the edge of the lake, turning its surface into molten gold...",
        type: "Prose",
        date: "Autumn, 2024",
        likes: 167,
        saves: 43,
        author: "Samuel Beckett",
    },
    {
        id: 144,
        title: "Whispers of the Wind",
        excerpt:
            "The wind carried stories of distant lands, its whispers echoing through the valleys and filling the night with mystery...",
        type: "Poetry",
        date: "Spring, 2024",
        likes: 133,
        saves: 44,
        author: "Fiona Harper",
    },
    {
        id: 145,
        title: "The Silent Hours",
        excerpt:
            "In those moments between dusk and darkness, when the world grows quiet and memories surface like stars in the evening sky...",
        type: "Prose",
        date: "Winter, 2024",
        likes: 156,
        saves: 42,
        author: "Eleanor Wells",
    },
    {
        id: 146,
        title: "Leaves of Yesterday",
        excerpt:
            "Autumn leaves whisper tales of seasons past,\nTheir golden hues a testament to time,\nDancing on winds both gentle and vast,\nNature's poetry in motion sublime.",
        type: "Poetry",
        date: "Autumn, 2024",
        likes: 123,
        saves: 38,
        author: "Thomas Blake",
    },
    {
        id: 147,
        title: "Letters from the Sea",
        excerpt:
            "The lighthouse keeper's daughter found the first bottle on a Tuesday morning, its glass worn smooth by the endless tides...",
        type: "Short Story",
        date: "Spring, 2024",
        likes: 189,
        saves: 56,
        author: "Marie Laurent",
    },
    {
        id: 148,
        title: "Morning Musings",
        excerpt:
            "Dawn breaks softly over the city walls,\nPainting shadows on ancient stone,\nWhile time slowly recalls,\nMemories we've known.",
        type: "Poetry",
        date: "Winter, 2024",
        likes: 144,
        saves: 47,
        author: "Christopher Reed",
    },
    {
        id: 149,
        title: "Shadows of Tomorrow",
        excerpt:
            "Beneath the looming skyscrapers, a boy dreams of stars unseen, of places untouched by the chaos of modern life...",
        type: "Prose",
        date: "Summer, 2024",
        likes: 132,
        saves: 34,
        author: "Amelia Kent",
    },
    {
        id: 150,
        title: "Echoes in the Fog",
        excerpt:
            "A lone figure moved through the dense fog, their footsteps echoing against cobblestones worn by centuries of history...",
        type: "Short Story",
        date: "Autumn, 2024",
        likes: 203,
        saves: 63,
        author: "Nathaniel Grey",
    },
    {
        id: 151,
        title: "Rain's Serenade",
        excerpt:
            "The rain plays its soft symphony on the windowpanes,\nEach drop a note, each pause a rest,\nNature's lullaby for the weary souls...",
        type: "Poetry",
        date: "Monsoon, 2024",
        likes: 158,
        saves: 41,
        author: "Isabella Hart",
    },
    {
        id: 152,
        title: "The Keeper of Lanterns",
        excerpt:
            "Every night, as the village slept, she walked the cobbled streets, lighting the lanterns and carrying stories in her wake...",
        type: "Prose",
        date: "Winter, 2024",
        likes: 187,
        saves: 54,
        author: "Julia Marlowe",
    },
    {
        id: 153,
        title: "Fragments of Dreams",
        excerpt:
            "In the silence of the midnight hour,\nDreams unravel their mysteries,\nWhispering secrets of the soul,\nIn fleeting moments of clarity.",
        type: "Poetry",
        date: "Spring, 2024",
        likes: 125,
        saves: 39,
        author: "Edward Holloway",
    },
    {
        id: 154,
        title: "Beneath the Willow Tree",
        excerpt:
            "As children, they carved their names into the tree\u2019s bark, a promise to never forget, even as the years pulled them apart...",
        type: "Short Story",
        date: "Summer, 2024",
        likes: 195,
        saves: 58,
        author: "Sophia Clarke",
    },
    {
        id: 155,
        title: "Songs of the Wild",
        excerpt:
            "Deep in the heart of the forest, where sunlight barely touched the earth, the call of the wild sang in untamed harmony...",
        type: "Prose",
        date: "Autumn, 2024",
        likes: 145,
        saves: 46,
        author: "Oliver Grant",
    },
    {
        id: 156,
        title: "Frost's Embrace",
        excerpt:
            "Winter wraps the world in its icy arms,\nA fleeting hush before spring's rebirth,\nIn its cold beauty, it charms,\nThe sleeping earth.",
        type: "Poetry",
        date: "Winter, 2024",
        likes: 139,
        saves: 37,
        author: "Lydia Vaughn",
    },
    {
        id: 157,
        title: "The Clockmaker's Secret",
        excerpt:
            "In the quiet of his workshop, surrounded by ticking timepieces, the clockmaker worked tirelessly, guarding a secret older than time...",
        type: "Short Story",
        date: "Spring, 2024",
        likes: 211,
        saves: 68,
        author: "Henry Adler",
    },
    {
        id: 158,
        title: "Threads of Gold",
        excerpt:
            "In the bustling marketplace, amidst the chaos of voices and colors, she wove tales of ancient legends with threads of gold...",
        type: "Prose",
        date: "Summer, 2024",
        likes: 172,
        saves: 49,
        author: "Annabelle Frost",
    },
    {
        id: 159,
        title: "Reflections at Dusk",
        excerpt:
            "As the sun dipped below the horizon, its final rays caught the edge of the lake, turning its surface into molten gold...",
        type: "Prose",
        date: "Autumn, 2024",
        likes: 167,
        saves: 43,
        author: "Samuel Beckett",
    },
    {
        id: 160,
        title: "Whispers of the Wind",
        excerpt:
            "The wind carried stories of distant lands, its whispers echoing through the valleys and filling the night with mystery...",
        type: "Poetry",
        date: "Spring, 2024",
        likes: 133,
        saves: 44,
        author: "Fiona Harper",
    },
];
export default stories;
