export const postDarkThemes = {
    oneDarkPro: {
        name: "One Dark Pro",
        colors: {
            bg: "dark:bg-[#282c34]",
            headerBg: "dark:bg-[#21252b]",
            primaryText: "text-[#abb2bf]",
            secondaryText: "text-[#9da5b4]",
            cardBg: "dark:bg-[#2c313a]",
            hoverBg: "dark:hover:bg-[#2c313a]",
            border: "dark:border-[#3e4451]",
            tagBg: "dark:bg-[#3e4451]",
            tagText: "dark:text-[#d3d7de]",
            icon: "dark:text-[#abb2bf]",
            table: {
                headerBg: "dark:bg-[#21252b]",
                rowBg: "dark:bg-[#282c34]",
                border: "dark:border-[#3e4451]",
            },
        },
    },
    ayuDark: {
        name: "Ayu Dark",
        colors: {
            bg: "dark:bg-[#0a0e14]",
            headerBg: "dark:bg-[#0d1017]",
            primaryText: "text-[#b3b1ad]",
            secondaryText: "text-[#828c99]",
            cardBg: "dark:bg-[#1c2028]",
            hoverBg: "dark:hover:bg-[#272d38]",
            border: "dark:border-[#253340]",
            tagBg: "dark:bg-[#253340]",
            tagText: "dark:text-[#e6b450]",
            icon: "dark:text-[#b3b1ad]",
            table: {
                headerBg: "dark:bg-[#0d1017]",
                rowBg: "dark:bg-[#0a0e14]",
                border: "dark:border-[#253340]",
            },
        },
    },
    dracula: {
        name: "Dracula",
        colors: {
            bg: "dark:bg-[#282a36]",
            headerBg: "dark:bg-[#1e1f29]",
            primaryText: "text-[#f8f8f2]",
            secondaryText: "text-[#bd93f9]",
            cardBg: "dark:bg-[#343746]",
            hoverBg: "dark:hover:bg-[#44475a]",
            border: "dark:border-[#44475a]",
            tagBg: "dark:bg-[#44475a]",
            tagText: "dark:text-[#8be9fd]",
            icon: "dark:text-[#f8f8f2]",
            table: {
                headerBg: "dark:bg-[#1e1f29]",
                rowBg: "dark:bg-[#282a36]",
                border: "dark:border-[#44475a]",
            },
        },
    },
    solarizedDark: {
        name: "Solarized Dark",
        colors: {
            bg: "dark:bg-[#002b36]",
            headerBg: "dark:bg-[#001e27]",
            primaryText: "text-[#839496]",
            secondaryText: "text-[#586e75]",
            cardBg: "dark:bg-[#073642]",
            hoverBg: "dark:hover:bg-[#0c4b5f]",
            border: "dark:border-[#073642]",
            tagBg: "dark:bg-[#073642]",
            tagText: "dark:text-[#2aa198]",
            icon: "dark:text-[#839496]",
            table: {
                headerBg: "dark:bg-[#001e27]",
                rowBg: "dark:bg-[#002b36]",
                border: "dark:border-[#073642]",
            },
        },
    },
    nightOwl: {
        name: "Night Owl",
        colors: {
            bg: "dark:bg-[#011627]",
            headerBg: "dark:bg-[#001122]",
            primaryText: "text-[#d6deeb]",
            secondaryText: "text-[#8badc1]",
            cardBg: "dark:bg-[#0e2a44]",
            hoverBg: "dark:hover:bg-[#1c3b57]",
            border: "dark:border-[#122d42]",
            tagBg: "dark:bg-[#122d42]",
            tagText: "dark:text-[#c792ea]",
            icon: "dark:text-[#d6deeb]",
            table: {
                headerBg: "dark:bg-[#001122]",
                rowBg: "dark:bg-[#011627]",
                border: "dark:border-[#122d42]",
            },
        },
    },
    monokai: {
        name: "Monokai",
        colors: {
            bg: "dark:bg-[#272822]",
            headerBg: "dark:bg-[#1e1f1c]",
            primaryText: "text-[#f8f8f2]",
            secondaryText: "text-[#a6e22e]",
            cardBg: "dark:bg-[#3e3d32]",
            hoverBg: "dark:hover:bg-[#49483e]",
            border: "dark:border-[#49483e]",
            tagBg: "dark:bg-[#49483e]",
            tagText: "dark:text-[#f92672]",
            icon: "dark:text-[#f8f8f2]",
            table: {
                headerBg: "dark:bg-[#1e1f1c]",
                rowBg: "dark:bg-[#272822]",
                border: "dark:border-[#49483e]",
            },
        },
    },
    light: {
        name: "Light",
        colors: {
            bg: "dark:bg-white",
            headerBg: "dark:bg-white",
            primaryText: "text-black",
            secondaryText: "text-black",
            cardBg: "dark:bg-gray-100",
            hoverBg: "dark:hover:bg-gray-200",
            border: "dark:border-gray-100",
            tagBg: "dark:bg-gray-100",
            tagText: "dark:text-gray-500",
            icon: "dark:text-gray-700",
            table: {
                headerBg: "dark:bg-white",
                rowBg: "dark:bg-gray-50",
                border: "dark:border-gray-100",
            },
        },
    },
};

/*ayuLight: {
    name: "Ayu Light",
    colors: {
        bg: "dark:bg-[#fafafa]",
        headerBg: "dark:bg-[#f3f3f3]",
        primaryText: "text-[#000]",
        secondaryText: "text-[#111]",
        cardBg: "dark:bg-[#ffffff]",
        hoverBg: "dark:hover:bg-[#f0f0f0]",
        border: "dark:border-[#d9dbde]",
        tagBg: "dark:bg-[#e6e8ea]",
        tagText: "dark:text-[#55b4d4]",
        icon: "dark:text-[#8a9199]",
        table: {
            headerBg: "dark:bg-[#f3f3f3]",
            rowBg: "dark:bg-[#ffffff]",
            border: "dark:border-[#d9dbde]",
        },
    },
}, */
