const express = require("express");
const multer = require("multer");
const axios = require("axios");
const FormData = require("form-data");

require("dotenv").config();
const router = express.Router();

// multer :: store uploaded file in mem
const storage = multer.memoryStorage();
const upload = multer({ storage });

// check file size && type again
router.post("/uploadImage", upload.single("image"), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: "No file provided" });
    }
    const { buffer, mimetype } = req.file;

    // FormData instance to send to Imgur
    const formData = new FormData();
    // Upload image as base64 encoded string
    formData.append("image", buffer.toString("base64"));
    formData.append("type", "base64");

    const clientId = process.env.IMGUR_CLIENT_ID;
    if (!clientId) {
      throw new Error("IMGUR_CLIENT_ID not set in environment variables");
    }

    // POST :: Imgur
    const response = await axios.post(
      "https://api.imgur.com/3/image",
      formData,
      {
        headers: {
          // spreading the headers generated by formData, including the correct multipart boundary
          ...formData.getHeaders(),
          Authorization: `Client-ID ${clientId}`,
        },
      },
    );

    // Check :: upload successful
    const { data } = response;
    if (!data.success) {
      return res.status(500).json({ error: "Imgur upload failed" });
    }

    const { link, deletehash } = data.data;

    // return the md img link & delete hash to the client
    res.status(200).json({
      directLink: link,
      imgDeleteHash: deletehash,
    });
  } catch (error) {
    console.error(
      "Error uploading image:",
      error.response?.data || error.message,
    );
    res.status(500).json({
      error:
        error.response?.data?.error || error.message || "An error occurred",
    });
  }
});

module.exports = { router };
